feat: update release please config

diff --git a/.azure/pipeline.yaml b/.azure/pipeline.yaml
--- a/.azure/pipeline.yaml
+++ b/.azure/pipeline.yaml
@@ -409,6 +409,11 @@ stages:
                       echo "Error: Failed to publish "@ogcio/design-system-tokens"."
                     fi
 
+                    echo "Publishing "@ogcio/design-system-fonts"..."
+                    if ! pnpm --filter "@ogcio/design-system-fonts" publish --no-git-checks --access public; then
+                      echo "Error: Failed to publish "@ogcio/design-system-fonts"."
+                    fi
+
                     echo "Creating dist"
                     pnpm run dist
 
