chore: fix pipeline

diff --git a/.azure/pipeline.yaml b/.azure/pipeline.yaml
--- a/.azure/pipeline.yaml
+++ b/.azure/pipeline.yaml
@@ -349,105 +349,105 @@ stages:
                     export TOKEN=$(aws secretsmanager get-secret-value --secret-id ${{ variables.npmjsSecret }} | jq --raw-output '.SecretString' | jq -r .TOKEN)
                     echo "##vso[task.setvariable variable=npmjsTokenADO;issecret=true;isoutput=true;]$TOKEN"
 
-  - stage: releaseLibraries
-    displayName: Release Libraries
-    dependsOn: retrieveCredentials
-    jobs:
-      - job: HandleRelease
-        variables:
-          - name: githubTokenADO
-            value: $[stageDependencies.retrieveCredentials.readCredentials.outputs['setGithubToken.githubTokenADO']]
-          - name: npmjsTokenADO
-            value: $[stageDependencies.retrieveCredentials.readCredentials.outputs['setNPMjsToken.npmjsTokenADO']]
-        displayName: Handle Release Process
-        pool:
-          vmImage: ${{ parameters.vmImage }}
-        steps:
-          - template: tools/install-pnpm.yml@pipeline-templates
+      - stage: releaseLibraries
+        displayName: Release Libraries
+        dependsOn: retrieveCredentials
+        jobs:
+          - job: HandleRelease
+            variables:
+              - name: githubTokenADO
+                value: $[stageDependencies.retrieveCredentials.readCredentials.outputs['setGithubToken.githubTokenADO']]
+              - name: npmjsTokenADO
+                value: $[stageDependencies.retrieveCredentials.readCredentials.outputs['setNPMjsToken.npmjsTokenADO']]
+            displayName: Handle Release Process
+            pool:
+              vmImage: ${{ parameters.vmImage }}
+            steps:
+              - template: tools/install-pnpm.yml@pipeline-templates
 
-          - task: Bash@3
-            name: setReleaseVariables
-            inputs:
-              targetType: "inline"
-              script: |
-                COMMIT_MESSAGE=$(git log -1 --pretty=%B)
-                echo "Commit Message: $COMMIT_MESSAGE"
-                echo "##vso[task.setvariable variable=COMMIT_MESSAGE;isOutput=true]$COMMIT_MESSAGE"
+              - task: Bash@3
+                name: setReleaseVariables
+                inputs:
+                  targetType: "inline"
+                  script: |
+                    COMMIT_MESSAGE=$(git log -1 --pretty=%B)
+                    echo "Commit Message: $COMMIT_MESSAGE"
+                    echo "##vso[task.setvariable variable=COMMIT_MESSAGE;isOutput=true]$COMMIT_MESSAGE"
 
-                if [[ $COMMIT_MESSAGE =~ ^"${{ parameters.autoReleaseCommitMessagePrefix }}" ]]; then
-                  echo "Publishing status: true"
-                  echo "##vso[task.setvariable variable=PUBLISH_PLEASE;isOutput=true]true"
-                else
-                  echo "Publishing status: false"
-                  echo "##vso[task.setvariable variable=PUBLISH_PLEASE;isOutput=true]false"
-                fi
-            env:
-              GITHUB_TOKEN: $(githubTokenADO)
+                    if [[ $COMMIT_MESSAGE =~ ^"${{ parameters.autoReleaseCommitMessagePrefix }}" ]]; then
+                      echo "Publishing status: true"
+                      echo "##vso[task.setvariable variable=PUBLISH_PLEASE;isOutput=true]true"
+                    else
+                      echo "Publishing status: false"
+                      echo "##vso[task.setvariable variable=PUBLISH_PLEASE;isOutput=true]false"
+                    fi
+                env:
+                  GITHUB_TOKEN: $(githubTokenADO)
 
-          # Create/Update the Release PR if on main branch and PUBLISH_PLEASE is "false"
-          - task: Bash@3
-            name: createReleasePR
-            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['setReleaseVariables.PUBLISH_PLEASE'], 'false'))
-            inputs:
-              targetType: "inline"
-              script: |
-                if [ -z "$GITHUB_TOKEN" ]; then
-                  echo "GITHUB_TOKEN is not set. Please set the GITHUB_TOKEN environment variable."
-                  exit 1
-                fi
+              # Create/Update the Release PR if on main branch and PUBLISH_PLEASE is "false"
+              - task: Bash@3
+                name: createReleasePR
+                condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['setReleaseVariables.PUBLISH_PLEASE'], 'false'))
+                inputs:
+                  targetType: "inline"
+                  script: |
+                    if [ -z "$GITHUB_TOKEN" ]; then
+                      echo "GITHUB_TOKEN is not set. Please set the GITHUB_TOKEN environment variable."
+                      exit 1
+                    fi
 
-                echo "Creating/Updating release pull request"
-                if ! npx release-please release-pr \
-                  --token="$GITHUB_TOKEN" \
-                  --repo-url="https://github.com/ogcio/govie-ds"; then
-                  echo "Error: Failed to create/update release pull request. Check the GITHUB_TOKEN and repoUrl."
-                  exit 1
-                fi
-            env:
-              GITHUB_TOKEN: $(githubTokenADO)
+                    echo "Creating/Updating release pull request"
+                    if ! npx release-please release-pr \
+                      --token="$GITHUB_TOKEN" \
+                      --repo-url="https://github.com/ogcio/govie-ds"; then
+                      echo "Error: Failed to create/update release pull request. Check the GITHUB_TOKEN and repoUrl."
+                      exit 1
+                    fi
+                env:
+                  GITHUB_TOKEN: $(githubTokenADO)
 
-          # Publish package only if on main branch and PUBLISH_PLEASE is true
-          - task: Bash@3
-            name: publishPackages
-            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['setReleaseVariables.PUBLISH_PLEASE'], 'true'))
-            inputs:
-              targetType: "inline"
-              script: |
-                if [ -z "$NPM_TOKEN" ]; then
-                  echo "NPM_TOKEN is not set. Please set the NPM_TOKEN environment variable."
-                  exit 1
-                fi
-                if [ -z "$GITHUB_TOKEN" ]; then
-                  echo "GITHUB_TOKEN is not set. Please set the GITHUB_TOKEN environment variable."
-                  exit 1
-                fi
+              # Publish package only if on main branch and PUBLISH_PLEASE is true
+              - task: Bash@3
+                name: publishPackages
+                condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['setReleaseVariables.PUBLISH_PLEASE'], 'true'))
+                inputs:
+                  targetType: "inline"
+                  script: |
+                    if [ -z "$NPM_TOKEN" ]; then
+                      echo "NPM_TOKEN is not set. Please set the NPM_TOKEN environment variable."
+                      exit 1
+                    fi
+                    if [ -z "$GITHUB_TOKEN" ]; then
+                      echo "GITHUB_TOKEN is not set. Please set the GITHUB_TOKEN environment variable."
+                      exit 1
+                    fi
 
-                echo "Creating GitHub release..."
-                if ! npx release-please github-release \
-                  --token="$GITHUB_TOKEN" \
-                  --repo-url="https://github.com/ogcio/govie-ds"; then
-                  echo "Error: Failed to create GitHub release. Check the GITHUB_TOKEN and repoUrl."
-                  exit 1
-                fi
+                    echo "Creating GitHub release..."
+                    if ! npx release-please github-release \
+                      --token="$GITHUB_TOKEN" \
+                      --repo-url="https://github.com/ogcio/govie-ds"; then
+                      echo "Error: Failed to create GitHub release. Check the GITHUB_TOKEN and repoUrl."
+                      exit 1
+                    fi
 
-                npm config set //registry.npmjs.org/:_authToken "$NPM_TOKEN"
+                    npm config set //registry.npmjs.org/:_authToken "$NPM_TOKEN"
 
-                pnpm run build:libs
+                    pnpm run build:libs
 
-                echo "Publishing "@ogcio/design-system-react"..."
-                if ! pnpm --filter "@ogcio/design-system-react" publish --no-git-checks --access public; then
-                  echo "Error: Failed to publish "@ogcio/design-system-react"."
-                fi
+                    echo "Publishing "@ogcio/design-system-react"..."
+                    if ! pnpm --filter "@ogcio/design-system-react" publish --no-git-checks --access public; then
+                      echo "Error: Failed to publish "@ogcio/design-system-react"."
+                    fi
 
-                echo "Publishing "@ogcio/theme-govie"..."
-                if ! pnpm --filter "@ogcio/theme-govie" publish --no-git-checks --access public; then
-                  echo "Error: Failed to publish "@ogcio/theme-govie"."
-                fi
-            env:
-              NPM_TOKEN: $(npmjsTokenADO)
-              GITHUB_TOKEN: $(githubTokenADO)
+                    echo "Publishing "@ogcio/theme-govie"..."
+                    if ! pnpm --filter "@ogcio/theme-govie" publish --no-git-checks --access public; then
+                      echo "Error: Failed to publish "@ogcio/theme-govie"."
+                    fi
+                env:
+                  NPM_TOKEN: $(npmjsTokenADO)
+                  GITHUB_TOKEN: $(githubTokenADO)
 
-  - stage: Chromatic HTML
+  - stage: Chromatic_HTML
     dependsOn: checkTestCompleted
     pool:
       vmImage: ${{ parameters.vmImage }}
@@ -474,7 +474,7 @@ stages:
             env:
               CHROMATIC_PROJECT_TOKEN: $(CHROMATIC_PROJECT_TOKEN_HTML)
 
-  - stage: Chromatic React
+  - stage: Chromatic_React
     dependsOn: checkTestCompleted
     pool:
       vmImage: ${{ parameters.vmImage }}
